[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = ["cd backend && npm ci --only=production"]

[phases.build]
cmds = ["cd backend && CI=false npm run build"]

[start]
cmd = "cd backend && npx prisma migrate deploy && node dist/server.js"
